export const {
  NEXT_PUBLIC_APPWRITE_ENDPOINT,
  NEXT_PUBLIC_APPWRITE_PROJECT: PROJECT_ID,
  NEXT_PUBLIC_APPWRITE_BUCKET: BUCKET_ID,
  APPWRITE_DATABASE: DATABASE_ID,
  APPWRITE_USERS_COLLECTION: USERS_COLLECTION_ID,
  APPWRITE_FILES_COLLECTION: FILES_COLLECTION_ID,
  APPWRITE_API_KEY: SECRET_KEY,
} = process.env;
